### ISSUE TITLE
Debuging doesn't work with parameter console: "integratedTerminal"

### ISSUE THREAD

**Issue by askeet** [rtbenfield/vscode-jest-test-adapter#24]
In the end  I've found that parameter  console: "integratedTerminal"  in the  vscode.DebugConfiguration doesn't working properly for my project. After I've deleted it  the debug mode for extenstion 0.1.3 starts to  work   for me    

Thank you

**Comment by rtbenfield** [comment]
Thanks for reporting this. I haven't been able to reproduce the problem on my machine, but I am adding an option in Settings to choose where the debug output should be piped. The available options will be the options specified for `console` in VS Code's documentation [here](https://code.visualstudio.com/Docs/editor/debugging#_launchjson-attributes). The default value will be `internalConsole`, which looks to be where the output goes if `console` is not specified.

**Comment by rtbenfield** [comment]
Version 0.1.3 has been published to the VS Code Marketplace that should resolve this issue.

**Comment by askeet** [comment]
> Version 0.1.3 has been published to the VS Code Marketplace that should resolve this issue.

Unfotenetly source maping  of Jest in debug mode  doesn't work in the project   
Could you also add option   to change  const args to  [
      "--runInBand",
      "--coverage=false",
      "--verbose=false",
    ];
