### ISSUE TITLE
Running test with double-quote in name results in entire fixture reported as pending

### ISSUE THREAD

**Issue by rythos42** [rtbenfield/vscode-jest-test-adapter#29]
`test('<AppealStatus status="NotSubmitted" />', () => {
  const wrapper = shallow(<AppealStatus status="NotSubmitted" />);

  expect(wrapper.text()).toEqual('- -');
});

test('<AppealStatus status="Submitted" />', () => {
  const wrapper = shallow(<AppealStatus status="Submitted" />);

  expect(wrapper.text()).toEqual('Submitted');
});`

Because the Jest `testNamePattern` uses double quotes to surround the pattern, any double quotes in the name cause issues when running the test.

**Comment by rtbenfield** [comment]
Resolved in #23.
