### ISSUE TITLE
Update README with proper instructions

### ISSUE THREAD

**Issue by rtbenfield** [rtbenfield/vscode-jest-test-adapter#6]
The project README should be updated with proper instructions for setting up and running the Jest test adapter. Any caveats or configuration "gotchas" should be noted as well.

**Comment by nonameolsson** [comment]
Is this the only issue left before you will publish the beta to Marketplace? Could we help somehow?

**Comment by rtbenfield** [comment]
I just pushed up a blurb in the README with basic instructions to get started. I'm about to begin looking into publishing to the Marketplace.

I could absolutely use help on this project. After getting published to the Marketplace, my next goal will be to make the extension flexible to a variety of environments and configurations. I would very much appreciate any help in testing and addressing issues in this effort.

**Comment by agnoam** [comment]
@rtbenfield, I have installed your plugin. and reloaded the vscode, but I didn't see anything at the test explorer. what should I do ?
